CorridaDeCachorros.Mvc/Models/ErrorViewModel.cs
namespace CorridaDeCachorros.Mvc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CorridaDeCachorros.Mvc/Controllers/CorridaDeCachorrosController.cs
using Microsoft.AspNetCore.Mvc;

namespace CorridaDeCachorros.Mvc.Controllers
{
    public class CorridaDeCachorrosController : Controller
    {
        public CorridaDeCachorro CorridaDeCachorro { get; set; }
        public static string SumarioCorrida { get; set; } = string.Empty;

        private static Task corridaEmExecucao { get; set; }

        public CorridaDeCachorrosController(
            CorridaDeCachorro corridaDeCachorro)
        {
            CorridaDeCachorro = corridaDeCachorro;
        }

        public IActionResult Index()
        {
            ViewData["SumarioCorrida"] = SumarioCorrida;
            var corridaIniciou = corridaEmExecucao != null ? true : false;
            ViewData["CorridaEmExecucao"] = corridaIniciou;
            return View(CorridaDeCachorro);
        }

        [HttpPost]
        public IActionResult Aposta(
            [Bind("nomeCorredor,nomeApostador,valorAposta")]
            string nomeCorredor, string nomeApostador, double valorAposta)
        {
            // Use the idDoCorredor parameter in your logic
            CorridaDeCachorro.Apostar(nomeApostador, nomeCorredor, valorAposta);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> CorrerAsync()
        {
            corridaEmExecucao = Task.Run(async () =>
            {
                if (SumarioCorrida.Length != 0)
                {
                    CorridaDeCachorro.ResetarCorrida();
                }
                SumarioCorrida = await CorridaDeCachorro.Correr();
                Task.Run(() =>
                {
                    Thread.Sleep(200);
                    corridaEmExecucao = null;
                });
            });

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult NovaCorrida()
        {
            if (SumarioCorrida.Length != 0)
            {
                CorridaDeCachorro.ResetarCorrida();
                SumarioCorrida = string.Empty;
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult AdicionarCachorro([Bind("nome_cachorro")] string nome_cachorro)
        {
            CorridaDeCachorro.AdicionarCorredor(nome_cachorro);

            return RedirectToAction("Index");
        }
    }
}

CorridaDeCachorros.Mvc/Views/CorridaDeCachorros/Index.cshtml
@model CorridaDeCachorros.CorridaDeCachorro

@{
    ViewData["Title"] = Model.GUID;
    string sumario = ViewData["SumarioCorrida"].ToString();
    var corridaIniciou = ((bool)ViewData["CorridaEmExecucao"]);
}


<div class="container mt-5">
    <div class="row">
        <div class="col-md-12">
            <div class="col-md-6">
                <h1 class="display-4">Total de apostas @Model.ValorTotalDeApostas</h1>
            </div>
            <div class="col-md-6">
                <h1 class="display-4">Valor sem ganhador @Model.ValorSemGanhador</h1>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-1">
            <form asp-controller="CorridaDeCachorros" asp-action="Correr" method="post">
                <button disabled="@(string.IsNullOrEmpty(sumario) is false)" type="submit" class="btn btn-success">Correr</button>
            </form>
        </div>
        <div class="col-md-2">
            <form asp-controller="CorridaDeCachorros" asp-action="NovaCorrida" method="post">
                <button disabled="@(string.IsNullOrEmpty(sumario) is true)" type="submit" class="btn btn-success">Nova Corrida</button>
            </form>
        </div>
    </div>
</div>


@if (!string.IsNullOrEmpty(sumario))
{
    <div class="container mt-5">
        <h1 class="display-4">Resultado da Corrida</h1>
        <div class="card">
            <div class="card-body">
                <textarea class="form-control" rows="5" readonly>@sumario</textarea>
            </div>
        </div>
    </div>
}

@if (Model.Apostadores.Exists(x => x.Apostou is false))
{
    <div class="container mt-5">
        <h1 class="display-4">Apostas</h1>
        <form asp-controller="CorridaDeCachorros" asp-action="Aposta" method="post">
            <div class="form-group">
                <label>Apostador:</label>

                @foreach (var item in Model.Apostadores.OrderBy(x => x.Apostou is true))
                {

                    <div class="form-check form-check-inline">
                        <input type="radio" id="@("apostador_" + item.Nome)" name="nomeApostador" class="form-check-input" value="@item.Nome" @(item.Apostou ? "disabled" : "") @(item.Apostou is false ? "checked" : "")>
                        <label for="@("apostador_" + item.Nome)" class="form-check-label">@item.Nome @(item.Apostou ? "(Apostou)" : "")</label>
                    </div>
                }
            </div>



            <div class="form-group">
                <label for="nomeCorredor">Cachorro:</label>
                <select id="nomeCorredor" name="nomeCorredor" class="form-select" aria-label="Selecione um cachorro">
                    @{
                        var selected = @Model.Corredores[0].Nome;
                    }
                    <option selected>@Model.Corredores[0].Nome</option>
                    @foreach (var item in Model.Corredores)
                    {
                        <option value="@item.Nome">@item.Nome</option>
                    }
                </select>
            </div>

            <div class="form-group">
                <label for="valorAposta">Valor da Aposta:</label>
                <input type="number" id="valorAposta" name="valorAposta" class="form-control" placeholder="Aqui digita a sua aposta" value="5" />
            </div>

            <div class="mt-3"></div>
            <button type="submit" class="btn btn-primary">Apostar</button>
        </form>

        <div class="mt-3"></div>


    </div>
}

<div class="container mt-5">
    <h2 class="text-center mb-4">Lista de Corredores</h2>
    <div class="list-group">
        @foreach (var item in Model.Corredores)
        {
            <div class="list-group-item mb-3">
                <div class="d-flex align-items-center justify-content-between">
                    <div style="width: 20%;">
                        <h4 class="mb-1">@item.Nome</h4>
                        <p class="text-muted">Distância Percorrida: <strong>@item.DistanciaPercorrida()</strong></p>
                        <p class="text-muted">Hora Da Saída: <strong>@item.HoraDaSaida.ToString("HH:mm:ss.fff")</strong></p>
                        <p class="text-muted">Hora Da Chegada: <strong>@item.HoraDaChegada.ToString("HH:mm:ss.fff")</strong></p>
                        <p class="text-muted">Tempo Percorrido: <strong>@item.TempoPercorrido.ToString(@"hh\:mm\:ss\.fff")</strong></p>
                    </div>
                    <div class="position-relative" style="padding-left:20%; width: 100%;">
                        <div class="bg-light rounded-pill" style="height: 10px; width: 100%; position: relative;">
                            <div class="position-absolute"
                                 style="height: 30px; width: 30px; top: -10px; left: @(item.DistanciaPercorridaWeb())px;">
                                <img src="~/svg/cachorro.svg" class="rounded" style="height: 30px;">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>


@* 
<div class="row">
    <div class="col-md-6">
        <form asp-controller="CorridaDeCachorros" asp-action="AdicionarCachorro" method="post">
            <div class="mb-3">
                <label for="nome_cachorro" class="form-label">Nome do cachorro</label>
                <input type="text" class="form-control" id="nome_cachorro" name="nome_cachorro" placeholder="Digite o nome do cachorro">
            </div>
            <button type="submit" class="btn btn-primary">Adicionar</button>
        </form>
    </div>
</div> *@

<div class="row">
    @if (Model.Corredores.Any())
    {
        <div class="col-md-6">
            <h1> Cachorros </h1>
            <br />
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Corredores![0].Id)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Corredores![0].Nome)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Corredores![0].Posicao)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Corredores![0]._distanciaPercorrida)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Corredores!)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Id)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Nome)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Posicao)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item._distanciaPercorrida)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }
    @if (Model.Apostadores.Any())
    {
        <div class="col-md-6">
            <h1> Apostadores </h1>
            <br />
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Apostadores![0].Nome)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Apostadores![0].Saldo)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Apostadores![0].CachorroApostado)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Apostadores!)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Nome)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Saldo)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CachorroApostado)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }
</div>

<script>
    console.log("Página carregada");
    function AtualizarPagina() {
        console.log("Atualizando a página");
        setTimeout("window.location.reload()", 1000);
    }
</script>

@if (corridaIniciou)
{
    <script>
        console.log("Corrida emexecucao");
        AtualizarPagina()
    </script>
}

CorridaDeCachorros.Mvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CorridaDeCachorros.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CorridaDeCachorros.Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CorridaDeCachorros.Mvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CorridaDeCachorros.Mvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CorridaDeCachorros" asp-action="Index">Corrida</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CorridaDeCachorros.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>